---
title: "Density-Based Spatial Clustering of Applications with Noise"
author: "Yusi Yao, Leo Kim, Xavier Akers, Annalise Broerman"
date: "2025-04-22"
fontsize: 9pt
classoption: "aspectratio=169"
output: 
  beamer_presentation: 
    fonttheme: professionalfonts
    highlight: kate
    theme: Rochester
header-includes:
- \definecolor{VTmaroon}{HTML}{861F41}
- \usecolortheme[named=VTmaroon]{structure}
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)

def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  paste0("\n \\", "footnotesize","\n\n", x, "\n\n \\normalsize")
})


```

## Introduction

Density-based spacial clustering of applications with noise (DBSCAN) is an unsupervised clustering technique that uses certain aspects of a dataset to form groups of data points.


## When Is This Useful? 

DBSCAN is useful for

## Example Image

medium.com image

## Advantages

- Separates high density vs. low density clusters well
- Handles outliers well by identifying them as noise
- Does not assume shape of clusters, helpful for real-world data
- Great for large datasets and can be efficient with O(n log n) complexity

## Disadvantages

- Clusters with similar densities are hard to separate
- High dimensional data can cause problems if it has too many dimensions
- Sensitive to choice of epsilon and MinPts
- Sensitive to noise
- Choosing parameters can be difficult


## The DBSCAN Algorithm

DBSCAN begins by dividing a dataset into a number of dimensions, n. Next, a shape with that number of dimensions is formed around each data point. The number of points around that shape is counted and considered a cluster. This cluster expands by counting how many points are near each data point within the cluster.


Check this

## Example Image

medium.com image

## Important Concepts: Core Points

Within the DBSCAN algorithm, core points have a minimum number of neighbor points, or MinPts, within an epsilon distance of the point itself.

## Important Concepts: Border Points

Border points have no minimum number of neighbor points near them and are within an epsilon distance of a core point.

## Important Concepts: Noise Points

Noise points are points that are neither core points or border points.

## Example Image

datacamp.com image

## Important Concepts: Density Reachability

## Important Concepts: Density Connectivity
